### ISSUE TITLE
FilteredForumSearch: Invalid Search Results for Discussions Without Comments

### ISSUE THREAD

**Issue by agcyphers** [TwistedTwigleg/godot-forums-vanilla-plugins#13]
I've recently begun using this add-on, but I'm having an issue with discussion results that are invalid. I'm using the latest version from the repository. It generates results with a URL like:

https://domain.com/forums/discussion/comment/#Comment_

They have no profile information or other metadata as seen in this image:
https://us.v-cdn.net/5018160/uploads/407/QQMVP0JGN1XS.png

Enabling the debug message at line 345 of class.searchmodel.php, I can see that all of the results that exhibit this issue are showing a DiscussionID of NULL, but they do have IDs in the database.

**Comment by TwistedTwigleg** [comment]
Hmm, strange. Which version of Vanilla are you using? We are using it with Vanilla 3.3 on the Godot Community forums and it works fine for us.

It sounds like the plugin is unable to retrieve the SQL data from the comments/topics when searching. I remember the Vanilla developers mentioning that they were going to make changes that might affect the plugin, so perhaps that is what is happening here...

Edit: Based on the title, I'm guessing it works okay for discussions with comments?

**Comment by agcyphers** [comment]
> Which version of Vanilla are you using?

3.3. We're less than a week in to moving back to Vanilla from bbPress.

> Based on the title, I'm guessing it works okay for discussions with comments?

Actually, looking at it now, it seems like if there are comments on the discussion then it returns the first comment (and/or any other comment) and not the discussion. If there aren't any comments, it returns the broken listing.

**Comment by agcyphers** [comment]
Enabled debugging and snagged this when running a search:
>Undefined variable: Session  #0 /forums/plugins/Index/default.php(53): gdn_ErrorHandler(8, 'Undefined varia...', '/home/graffi98/...', 53, Array) #1 [internal function]: IndexPlugin->Base_Render_Before(Object(SearchController), Array) #2 /forums/library/Garden/EventManager.php(278): call_user_func_array(Array, Array) #3 /forums/library/core/class.pluginmanager.php(810): Garden\EventManager->fire('Base_Render_Bef...', Object(SearchController), Array) #4 /forums/library/core/class.pluginmanager.php(773): Gdn_PluginManager->callEventHandler(Object(SearchController), 'Base', 'Render', 'Before') #5 /forums/library/core/class.pluggable.php(205): Gdn_PluginManager->callEventHandlers(Object(SearchController), 'SearchControlle...', 'Render', 'Before') #6 /forums/plugins/FilteredForumSearch/class.filteredforumsearch.plugin.php(94): Gdn_Pluggable->__call('Render', Array) #7 /forums/library/core/class.dispatcher.php(872): FilteredForumSearchPlugin->SearchController_Index_Create(Object(SearchController), '') #8 /forums/library/core/class.dispatcher.php(289): Gdn_Dispatcher->dispatchController(Object(Gdn_Request), Array) #9 /forums/index.php(29): Gdn_Dispatcher->dispatch() #10 {main}


>Notice | Gdn_Form->InputPrefix is deprecated  #0 [internal function]: gdn_ErrorHandler(16384, 'Gdn_Form->Input...', '/home/graffi98/...', 170, Array) #1 /forums/library/core/class.form.php(170): trigger_error('Gdn_Form->Input...', 16384) #2 /forums/plugins/FilteredForumSearch/views/index.php(7): Gdn_Form->__set('InputPrefix', '') #3 /forums/library/core/class.controller.php(782): include('/home/graffi98/...') #4 /forums/library/core/class.controller.php(1386): Gdn_Controller->fetchView('', false, false) #5 /forums/library/core/class.pluggable.php(217): Gdn_Controller->xRender() #6 /forums/plugins/FilteredForumSearch/class.filteredforumsearch.plugin.php(94): Gdn_Pluggable->__call('Render', Array) #7 /forums/library/core/class.dispatcher.php(872): FilteredForumSearchPlugin->SearchController_Index_Create(Object(SearchController), '') #8 /forums/library/core/class.dispatcher.php(289): Gdn_Dispatcher->dispatchController(Object(Gdn_Request), Array) #9 /forums/index.php(29): Gdn_Dispatcher->dispatch() #10 {main}

**Comment by agcyphers** [comment]
I know where the top one is coming from. That's something I'm working on and should be unrelated as it was a change I just made a bit ago.

**Comment by agcyphers** [comment]
I did see this at line 90 of class.searchmodel.php, maybe related?
```
// TwistedTwigleg note:
// Fixes issue where discussion title has to have a post in order to be searched. Not sure if it changes how search
// results act though. From my testing it does not seem to make any difference.
```

**Comment by TwistedTwigleg** [comment]
> I know where the top one is coming from. That's something I'm working on and should be unrelated as it was a change I just made a bit ago.

From my limited PHP and Vanilla experience, the second issue seems to be related to the UI in the plugin, rather than the plugin itself. It is likely because there is no error checking in the plugin for getting empty/strange results, which is causing the issue there.

> I did see this at line 90 of class.searchmodel.php, maybe related?

It might be. I was having the issue where discussions that had no comments were *not* showing up, and the fix at line 90 fixed the issue. Maybe remove the fix (comment out lines 93 and 94) and see if that fixes the issue? Though unfortunately, discussions without any comments will likely just not show up in the results at all. Might be worth a shot though.

(Aside: looking at the source in GitHub, evidently my IDE messed up the indent styles! 😅 )

**Comment by agcyphers** [comment]
Yeah, removing the lines at Line 90 just causes SQL errors.

**Comment by agcyphers** [comment]
I feel like part of the problem is going to be in lines 360-362. That looks like it would only work on comments and not discussions. I also noticed some SQL conditions that applied only to comments and not discussions. I'm working on sorting that out now.

**Comment by agcyphers** [comment]
I just can't figure out why the DiscussionIDs are NULL in the results. Makes no sense. The other data is populated.

EDIT: I'm betting it's line 94 that's killing the DiscussionID.
EDIT2: Scratch that. I'm overworked.

**Comment by TwistedTwigleg** [comment]
Hmm, maybe something is not being parsed correctly? Perhaps something changed the name, or the capitalization or something minor like that.

If you uncomment out line 345 in class.searchmodel.php, is `DiscussionID` (or something similar) one of the included fields?

**Comment by agcyphers** [comment]
Here's one of the broken results:
```
array (
  'DiscussionID' => NULL,
  'Type' => NULL,
  'ForeignID' => NULL,
  'CategoryID' => 20,
  'InsertUserID' => NULL,
  'UpdateUserID' => NULL,
  'FirstCommentID' => 0,
  'LastCommentID' => 0,
  'Name' => 'Test Tile',
  'Body' => NULL,
  'Format' => NULL,
  'Tags' => NULL,
  'CountComments' => 0,
  'CountBookmarks' => NULL,
  'CountViews' => 23,
  'Closed' => 1,
  'Announce' => 2,
  'Sink' => 0,
  'DateInserted' => NULL,
  'DateUpdated' => NULL,
  'InsertIPAddress' => NULL,
  'UpdateIPAddress' => NULL,
  'DateLastComment' => '2017-12-06 08:09:55',
  'LastCommentUserID' => 1,
  'Score' => NULL,
  'Attributes' => NULL,
  'RegardingID' => NULL,
  'QnA' => NULL,
  'DateAccepted' => NULL,
  'DateOfAnswer' => NULL,
  'Prefix' => NULL,
  'CommentID' => NULL,
  'DeleteUserID' => NULL,
  'DateDeleted' => NULL,
  'Flag' => NULL,
  'AcceptedUserID' => NULL,
)
```

**Comment by TwistedTwigleg** [comment]
Huh. Well, it's getting something, since the views and title are there. Strange that the body and discussion ID are null.
I guess another thing to check is to double check that the SQL database actually has the required fields for the search. In particular, `DiscussionID`. If it does, maybe double check the spelling and see if there is something off there? Maybe the plugin needs to check for both capitalized and capitalized fields or something.

Outside of that, I'm not really sure, sorry! It's hard to say what could be causing the issue without being able to replicate it. It is obviously getting something, so the SQL search is at least somewhat working, but for some reason the data returned by SQL is giving NULLs, that or PHP is.

Edit: You mentioned migrating the forums from bbPress. Do new Vanilla posts have this issue? Especially new Vanilla posts that have no comments? Maybe something in the import settings is changed the field names, and that is causing the issue.

**Comment by agcyphers** [comment]
The entire database was imported, and only those discussions with no comments are effected. If I manually go to one of the URLs (IE: domain.com/dicussions/9999/) the discussion pulls up just fine. Likewise if I navigate to it from the Category view.

**Comment by agcyphers** [comment]
I've just confirmed that this happens with new discussions that have no comments, as well. Has to be something in the SQL we're both overlooking.

**Comment by TwistedTwigleg** [comment]
Yeah, I'm guessing it is something with the SQL, though what, I cannot say. My guess is it is something minor, like a *slight* name mismatch with a field or something.

**Comment by agcyphers** [comment]
Yeah, I've checked the table schema. The only thing I could think of was the case on the table definitions in the plugin:
> gdn_discussion

versus the case in the actual database:
> GDN_Discussion

But changing that seemed to have no effect.

**Comment by agcyphers** [comment]
Is what's in the repo what you're currently running on your live site? Are you able to return search results matching Discussions with no Comments?

**Comment by TwistedTwigleg** [comment]
> Is what's in the repo what you're currently running on your live site? Are you able to return search results matching Discussions with no Comments?

We are using the version as the repository. However, it appears that for us, any new discussions with no comments in them made after we updated to Vanilla 3.3 have the same issue.
My guess is that something changed between Vanilla 3.2 and 3.3, and that is causing the issue. Unfortunately, right now (and likely in the short-term future) I do not have the time to investigate the issue further.
Good to have it confirmed and possible to replicate though! It means there is a chance I will be able to fix it once I have the time.

**Comment by agcyphers** [comment]
Good deal. I'm going to keep messing with it and I'll post a pull request if I sort it out.
